Redo workflows

diff --git a/.github/workflows/prevent-pushes-main.yaml b/.github/workflows/prevent-pushes-main.yaml
--- a/.github/workflows/prevent-pushes-main.yaml
+++ b/.github/workflows/prevent-pushes-main.yaml
@@ -1,20 +1,20 @@
 # This program is distributed under the terms of the GNU General Public License.
 # For more details, see the LICENSE file in the root of the repository.
 
-name: Non-Main Branch Push Checks
+name: Prevent Commits on Main Branch
 
 on:
     push:
-        branches-ignore:
+        branches:
             - main
 
 jobs:
-    prevent-push:
+    prevent-commit:
         runs-on: ubuntu-latest
         steps:
-            - name: Check push branch
+            - name: Check commit branch
               run: |
                   if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
-                    echo "Error: Pushes from the main branch are not allowed." >&2
+                    echo "Error: Commits to the main branch are not allowed." >&2
                     exit 1
                   fi
